import {useTeacherDraft} from './useTeacherDraft.js';
import {React,apiClient,useQueryClient} from './runtime.js';
import {blankSlide,slideId} from '../../shared/slide-document.js';
import {LessonAIAssistant} from './LessonAIAssistant.jsx';
import './elearning-studio.css';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
const copy=v=>structuredClone(v);
const textBox=()=>({id:slideId(),type:'text',x:10,y:15,w:70,h:20,text:'Nhập nội dung tại bảng bên phải',fontSize:32,color:'#203d50',background:'#ffffff',transparent:true,bold:false,align:'left'});
const quizBox=q=>({id:slideId(),type:'quiz',x:7,y:8,w:86,h:84,question:q?.question||'Nhập câu hỏi của bạn',options:q?.options||['Đáp án A','Đáp án B','Đáp án C','Đáp án D'],correct:q?.correctAnswer??0,explanation:q?.explanation||''});
function Artwork({item}){
  if(item.type==='image')return <img src={item.src} alt={item.alt} draggable={false} style={{objectFit:item.fit}}/>;
  if(item.type==='text')return <div className="slide-text" style={{fontSize:`${item.fontSize/9.6}cqw`,color:item.color,background:item.transparent?'transparent':item.background,fontWeight:item.bold?700:400,textAlign:item.align}}>{item.text}</div>;
  return <div className="slide-quiz"><strong>{item.question}</strong>{item.options.map((o,i)=><div key={i}>{String.fromCharCode(65+i)}. {o}{i===item.correct?' ✓':''}</div>)}</div>;
}
export function ElearningStudio({classId}){
  const base=`/classes/${classId}/elearning-studio`,cache=useQueryClient();
  const [showAssistant,setShowAssistant]=React.useState(false);
  const [doc,setDoc]=useTeacherDraft(base,'document',()=>({title:'Bài giảng mới',description:'',slides:[blankSlide()]})),[draft,setDraft]=useTeacherDraft(base,'saved',null),[drafts,setDrafts]=React.useState([]),[active,setActive]=React.useState(0),[selected,setSelected]=React.useState(null),[dirty,setDirty]=useTeacherDraft(base,'dirty',false),[busy,setBusy]=React.useState(''),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[preview,setPreview]=React.useState(''),[showAI,setShowAI]=React.useState(false),[context,setContext]=React.useState(''),[count,setCount]=React.useState(3),[,setHistoryVersion]=React.useState(0);
  const canvas=React.useRef(null),fileInput=React.useRef(null),drag=React.useRef(null),slideDrag=React.useRef(null),history=React.useRef({past:[],future:[]}),latest=React.useRef(doc);latest.current=doc;
  const slide=doc.slides[active],item=slide.items.find(i=>i.id===selected);
  const remember=()=>{history.current.past.push(copy(latest.current));history.current.past=history.current.past.slice(-60);history.current.future=[];setHistoryVersion(v=>v+1);};
  const change=(fn,record=true)=>{if(record)remember();setDoc(d=>{const next=fn(copy(d));latest.current=next;return next;});setDirty(true);setPreview('');};
  const updateItem=(patch,record=true)=>change(d=>{d.slides[active].items=d.slides[active].items.map(i=>i.id===selected?{...i,...patch}:i);return d;},record);
  const addItem=o=>{if(latest.current.slides[active].items.length>=30){setError('Mỗi trang tối đa 30 đối tượng.');return;}change(d=>{d.slides[active].items.push(o);return d;});setSelected(o.id);};
  const accept=d=>{setDraft(d);setDrafts(list=>[d,...list.filter(x=>x._id!==d._id)]);setDirty(false);return d;};
  React.useEffect(()=>{let alive=true;apiClient.get(base).then(r=>{if(alive)setDrafts(r.data.drafts);}).catch(()=>{if(alive)setError('Không tải được danh sách bản nháp.');});return()=>{alive=false;};},[base]);
  React.useEffect(()=>{if(!preview)return;const previous=document.activeElement;const key=e=>{if(e.key==='Escape')setPreview('');};const focus=e=>{const dialog=document.querySelector('.lesson-preview-overlay');if(dialog&&!dialog.contains(e.target))dialog.querySelector('button')?.focus();};document.addEventListener('keydown',key);document.addEventListener('focusin',focus);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('focusin',focus);previous?.focus?.();};},[preview]);
  const save=async()=>{if(!draft)return accept((await apiClient.post(base,latest.current)).data.draft);if(!dirty)return draft;return accept((await apiClient.patch(`${base}/${draft._id}`,{revision:draft.revision,document:latest.current})).data.draft);};
  const run=async(label,fn)=>{setBusy(label);setError('');setNotice('');try{await fn();}catch(e){setError(e.response?.data?.error||e.message||'Không thể thực hiện.');}finally{setBusy('');}};
  const open=d=>{setShowAssistant(false);setDoc(copy(d.document));latest.current=copy(d.document);accept(d);setActive(0);setSelected(null);setPreview('');history.current={past:[],future:[]};};
  const addSlide=()=>{if(doc.slides.length>=40)return;change(d=>{d.slides.splice(active+1,0,blankSlide());return d;});setActive(active+1);setSelected(null);};
  const reorder=(from,to)=>{if(to<0||to>=doc.slides.length||from===to)return;change(d=>{const [s]=d.slides.splice(from,1);d.slides.splice(to,0,s);return d;});setActive(to);setSelected(null);};
  const uploadImage=file=>run('Đang tải ảnh…',async()=>{if(!file)return;if(file.size>10*1024*1024)throw Error('Ảnh tối đa 10 MB.');let bitmap;try{bitmap=await createImageBitmap(file);}catch{throw Error('Chọn ảnh PNG, JPEG hoặc WebP hợp lệ.');}bitmap.close();const saved=await save(),form=new FormData();form.set('image',file);const r=await apiClient.post(`${base}/${saved._id}/images`,form,{headers:{'Content-Type':'multipart/form-data'}});addItem({id:slideId(),type:'image',x:20,y:18,w:50,h:60,src:r.data.url,alt:file.name.slice(0,200),fit:'contain'});});
  const startDrag=(e,o,resize=false)=>{if(busy||e.button!==0)return;e.stopPropagation();e.preventDefault();setSelected(o.id);remember();drag.current={id:o.id,x:e.clientX,y:e.clientY,original:copy(o),rect:canvas.current.getBoundingClientRect(),resize};e.currentTarget.setPointerCapture(e.pointerId);};
  const moveDrag=e=>{const d=drag.current;if(!d)return;const dx=(e.clientX-d.x)/d.rect.width*100,dy=(e.clientY-d.y)/d.rect.height*100,o=d.original;const patch=d.resize?{w:clamp(o.w+dx,5,100-o.x),h:clamp(o.h+dy,5,100-o.y)}:{x:clamp(o.x+dx,0,100-o.w),y:clamp(o.y+dy,0,100-o.h)};change(next=>{next.slides[active].items=next.slides[active].items.map(i=>i.id===d.id?{...i,...patch}:i);return next;},false);};
  const undo=redo=>{const h=history.current,from=redo?h.future:h.past,to=redo?h.past:h.future;if(!from.length)return;to.push(copy(latest.current));const next=from.pop();latest.current=next;setDoc(next);setActive(i=>Math.min(i,next.slides.length-1));setSelected(null);setDirty(true);setPreview('');};
  const removeItem=()=>{change(d=>{d.slides[active].items=d.slides[active].items.filter(i=>i.id!==selected);return d;});setSelected(null);};
  return <section className="lesson-studio" aria-label="Thiết kế bài giảng E-learning">
    <header className="lesson-heading"><div><span>KHÔNG GIAN SOẠN BÀI</span><h2>Bài giảng E-learning</h2><p>Kéo ảnh, đặt khung chữ và tạo câu hỏi ngay trên từng trang.</p></div><div className="class-actions"><button disabled={!!busy} className="secondary" onClick={()=>run('Đang lưu…',async()=>{if(dirty)await save();const next={title:'Bài giảng mới',description:'',slides:[blankSlide()]};setShowAssistant(false);setDoc(next);latest.current=next;setDraft(null);setDirty(false);setActive(0);setSelected(null);setPreview('');history.current={past:[],future:[]};})}>＋ Bài mới</button><button disabled={!!busy} onClick={()=>run('Đang lưu bản nháp…',async()=>{await save();setNotice('Đã lưu bản nháp.');})}>Lưu bản nháp</button></div></header>
    {error&&<p className="class-error" role="alert">{error}</p>}{(notice||busy)&&<p className="lesson-notice" role="status">{busy||notice}</p>}
    <fieldset className="lesson-controls" disabled={!!busy}>
    <div className="lesson-meta"><label className="class-field">Tên bài giảng<input maxLength={200} value={doc.title} onChange={e=>change(d=>({...d,title:e.target.value}))}/></label><label className="class-field">Mở bài đã lưu<select aria-label="Mở bài giảng đã lưu" value={draft?._id||''} onChange={e=>{const target=drafts.find(d=>d._id===e.target.value);if(target)run('Đang lưu…',async()=>{if(dirty)await save();open(target);});}}><option value="">Chọn bài giảng</option>{drafts.map(d=><option key={d._id} value={d._id}>{d.document.title} · {d.document.slides.length} trang</option>)}</select></label><span className="lesson-save-status">{dirty?'Có thay đổi chưa lưu':draft?'Đã lưu':'Bản mới'}</span></div>
    <div className="lesson-toolbar"><button type="button" className="lesson-ai-primary" onClick={()=>{setShowAssistant(v=>!v);setShowAI(false);}}>✦ AI hỗ trợ</button><button type="button" onClick={()=>addItem(textBox())} disabled={slide.items.length>=30}>T Khung chữ</button><button type="button" onClick={()=>fileInput.current.click()} disabled={slide.items.length>=30}>▧ Thêm ảnh</button><input ref={fileInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)uploadImage(file);}}/><button type="button" onClick={()=>addItem(quizBox())} disabled={slide.items.length>=30}>? Câu hỏi</button><button type="button" className="lesson-ai-button" onClick={()=>setShowAI(v=>!v)}>✦ Tạo câu hỏi AI</button><div className="lesson-toolbar-spacer"/><button type="button" disabled={!history.current.past.length} onClick={()=>undo(false)} aria-label="Hoàn tác">↶</button><button type="button" disabled={!history.current.future.length} onClick={()=>undo(true)} aria-label="Làm lại">↷</button><button type="button" onClick={()=>run('Đang dựng bản xem thử…',async()=>{const d=await save();setPreview((await apiClient.post(`${base}/${d._id}/preview`)).data.url);})}>▷ Xem thử</button></div>
    {showAI&&<section className="lesson-ai-panel"><div><h3>Tạo câu hỏi từ nội dung bài</h3><p>Gemini đọc nội dung chữ trong các trang. Mỗi câu được thêm thành một trang luyện tập; bạn có thể sửa câu hỏi, đáp án và giải thích.</p><label className="class-field">Tư liệu bổ sung<textarea aria-label="Tư liệu tạo câu hỏi" rows={3} value={context} maxLength={10000} onChange={e=>setContext(e.target.value)} placeholder="Dán thêm nội dung nếu các trang chưa có đủ chữ…"/></label></div><div><label className="class-field">Số câu hỏi<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button type="button" onClick={()=>run('Gemini đang tạo câu hỏi và đáp án…',async()=>{if(doc.slides.length+count>40)throw Error('Bài giảng tối đa 40 trang.');const d=await save();const r=await apiClient.post(`${base}/${d._id}/questions`,{count,context},{timeout:180000});const additions=r.data.questions.map(q=>({...blankSlide(),background:'#eaf4f8',items:[quizBox(q)]}));const index=latest.current.slides.length;change(next=>({...next,slides:[...next.slides,...additions]}));setActive(index);setSelected(additions[0].items[0].id);setShowAI(false);setNotice(`Đã thêm ${additions.length} trang câu hỏi. Kiểm tra đáp án rồi lưu bài.`);})}>Tạo câu hỏi</button></div></section>}
    {showAssistant&&<LessonAIAssistant base={base} title={doc.title} initialSource={draft?.aiSource} onPrepare={save} onRun={run} onClose={()=>setShowAssistant(false)} onComplete={d=>{open(d);setShowAssistant(false);setShowAI(false);setNotice(`AI đã tạo ${d.document.slides.length} trang và lưu bản nháp mới. Kiểm tra nội dung, ảnh và đáp án trước khi giao bài.`);}}/>}
    <div className="lesson-editor"><aside className="lesson-slides"><h3>TRANG <span>{doc.slides.length}</span></h3><div className="lesson-slide-list">{doc.slides.map((s,i)=><button type="button" className={`lesson-thumb ${i===active?'active':''}`} key={s.id} draggable={!busy} onDragStart={e=>{slideDrag.current=i;e.dataTransfer.setData("text/plain",String(i));e.dataTransfer.effectAllowed="move";}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(slideDrag.current!==null)reorder(slideDrag.current,i);slideDrag.current=null;}} onDragEnd={()=>{slideDrag.current=null;}} onClick={()=>{setActive(i);setSelected(null);}} aria-label={`Chọn trang ${i+1}`} aria-current={i===active?'page':undefined}><div className="lesson-mini" style={{background:s.background}}>{s.items.map(o=><div key={o.id} style={{position:'absolute',left:o.x+'%',top:o.y+'%',width:o.w+'%',height:o.h+'%',overflow:'hidden'}}><Artwork item={o}/></div>)}</div><span>{String(i+1).padStart(2,'0')}{s.items.some(o=>o.type==='quiz')?' · Câu hỏi':''}</span></button>)}</div><button type="button" className="secondary" disabled={doc.slides.length>=40} onClick={addSlide}>＋ Trang</button><div className="lesson-slide-actions"><button type="button" aria-label="Đưa trang lên" disabled={active===0} onClick={()=>reorder(active,active-1)}>↑</button><button type="button" aria-label="Đưa trang xuống" disabled={active===doc.slides.length-1} onClick={()=>reorder(active,active+1)}>↓</button></div></aside>
    <div className="lesson-workarea"><div className="lesson-canvas" ref={canvas} style={{background:slide.background}} onPointerDown={()=>setSelected(null)} onDragOver={e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();}} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])uploadImage(e.dataTransfer.files[0]);}}>{slide.items.map(o=><div className={`lesson-object ${selected===o.id?'selected':''}`} key={o.id} style={{left:o.x+'%',top:o.y+'%',width:o.w+'%',height:o.h+'%'}} tabIndex={0} role="group" aria-label={`${o.type==='text'?'Khung chữ':o.type==='image'?'Ảnh':'Câu hỏi'} trên trang`} onPointerDown={e=>startDrag(e,o)} onPointerMove={moveDrag} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onFocus={()=>setSelected(o.id)} onKeyDown={e=>{if(busy)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const n=e.shiftKey?5:1;updateItem({x:clamp(o.x+(e.key==='ArrowRight'?n:e.key==='ArrowLeft'?-n:0),0,100-o.w),y:clamp(o.y+(e.key==='ArrowDown'?n:e.key==='ArrowUp'?-n:0),0,100-o.h)});}if(e.key==='Delete'){e.preventDefault();removeItem();}}}><Artwork item={o}/>{selected===o.id&&<button type="button" className="lesson-resize" aria-label="Kéo đổi kích thước" onPointerDown={e=>startDrag(e,o,true)} onPointerMove={moveDrag} onPointerUp={e=>{e.stopPropagation();drag.current=null;}}/>}</div>)}{!slide.items.length&&<div className="lesson-empty"><span>＋</span><h3>Trang thiết kế của bạn</h3><p>Thêm khung chữ hoặc kéo ảnh từ máy vào đây.</p></div>}</div><div className="lesson-canvas-caption"><span>Trang {active+1}/{doc.slides.length} · Tỉ lệ 16:9</span><span>Kéo để di chuyển · Kéo góc để đổi cỡ · Phím mũi tên để căn chỉnh</span></div><div className="lesson-page-actions"><button type="button" className="secondary" disabled={doc.slides.length>=40} onClick={()=>{const duplicate=copy(slide);duplicate.id=slideId();duplicate.items.forEach(o=>o.id=slideId());change(d=>{d.slides.splice(active+1,0,duplicate);return d;});setActive(active+1);setSelected(null);}}>Nhân đôi trang</button><button type="button" className="secondary" disabled={doc.slides.length===1} onClick={()=>{change(d=>{d.slides.splice(active,1);return d;});setActive(Math.max(0,active-1));setSelected(null);}}>Xóa trang</button></div></div>
    <aside className="lesson-inspector"><h3>{item?'Thuộc tính đối tượng':'Thiết kế trang'}</h3><label className="class-field">Màu nền trang<input aria-label="Màu nền trang" type="color" value={slide.background} onChange={e=>change(d=>{d.slides[active].background=e.target.value;return d;})}/></label><div className="lesson-swatches">{['#fffaf0','#ffffff','#eaf4f8','#efeafb','#e8f3eb','#26394d'].map(c=><button type="button" key={c} style={{background:c}} aria-label={`Nền ${c}`} onClick={()=>change(d=>{d.slides[active].background=c;return d;})}/>)}</div>
    {!item?<p>Chọn ảnh hoặc khung chữ để chỉnh nội dung, kích thước và màu sắc.</p>:<><div className="lesson-geometry">{[['x','Vị trí X',0,100-item.w],['y','Vị trí Y',0,100-item.h],['w','Chiều rộng',5,100-item.x],['h','Chiều cao',5,100-item.y]].map(([key,label,min,max])=><label className="class-field" key={key}>{label} (%)<input aria-label={label} type="number" step={1} min={min} max={max} value={Math.round(item[key]*10)/10} onChange={e=>{if(e.target.value!=='')updateItem({[key]:clamp(Number(e.target.value),min,max)});}}/></label>)}</div>
    {item.type==='text'&&<><label className="class-field">Nội dung chữ<textarea aria-label="Nội dung khung chữ" rows={6} maxLength={4000} value={item.text} onChange={e=>updateItem({text:e.target.value})}/></label><label className="class-field">Cỡ chữ<input type="number" min={12} max={80} value={item.fontSize} onChange={e=>{if(e.target.value)updateItem({fontSize:clamp(Number(e.target.value),12,80)});}}/></label><div className="lesson-colors"><label className="class-field">Màu chữ<input type="color" value={item.color} onChange={e=>updateItem({color:e.target.value})}/></label><label className="class-field">Nền khung<input type="color" value={item.background} onChange={e=>updateItem({background:e.target.value,transparent:false})}/></label></div><label className="lesson-check"><input type="checkbox" checked={item.bold} onChange={e=>updateItem({bold:e.target.checked})}/>In đậm</label><label className="lesson-check"><input type="checkbox" checked={item.transparent} onChange={e=>updateItem({transparent:e.target.checked})}/>Nền trong suốt</label><label className="class-field">Căn chữ<select value={item.align} onChange={e=>updateItem({align:e.target.value})}><option value="left">Trái</option><option value="center">Giữa</option><option value="right">Phải</option></select></label></>}
    {item.type==='image'&&<><label className="class-field">Mô tả ảnh<input maxLength={200} value={item.alt} onChange={e=>updateItem({alt:e.target.value})}/></label><label className="class-field">Cách đặt ảnh<select value={item.fit} onChange={e=>updateItem({fit:e.target.value})}><option value="contain">Hiện toàn bộ ảnh</option><option value="cover">Lấp đầy khung</option></select></label></>}
    {item.type==='quiz'&&<><label className="class-field">Câu hỏi<textarea aria-label="Nội dung câu hỏi" maxLength={1000} value={item.question} onChange={e=>updateItem({question:e.target.value})}/></label>{item.options.map((o,i)=><label className="class-field" key={i}>Đáp án {String.fromCharCode(65+i)}<input maxLength={400} value={o} onChange={e=>updateItem({options:item.options.map((v,j)=>j===i?e.target.value:v)})}/></label>)}<label className="class-field">Đáp án đúng<select aria-label="Đáp án đúng" value={item.correct} onChange={e=>updateItem({correct:Number(e.target.value)})}>{item.options.map((o,i)=><option key={i} value={i}>{String.fromCharCode(65+i)}</option>)}</select></label><label className="class-field">Giải thích<textarea aria-label="Giải thích đáp án" value={item.explanation} maxLength={2000} onChange={e=>updateItem({explanation:e.target.value})}/></label></>}
    <div className="lesson-object-actions"><button type="button" className="secondary" onClick={()=>change(d=>{const items=d.slides[active].items;const i=items.findIndex(o=>o.id===selected);if(i<items.length-1)[items[i],items[i+1]]=[items[i+1],items[i]];return d;})}>Lên một lớp</button><button type="button" className="secondary" onClick={()=>change(d=>{const items=d.slides[active].items;const i=items.findIndex(o=>o.id===selected);if(i>0)[items[i],items[i-1]]=[items[i-1],items[i]];return d;})}>Xuống một lớp</button><button type="button" className="secondary" onClick={removeItem}>Xóa đối tượng</button></div></>}
    </aside></div>
    <div className="lesson-publish"><label className="class-field">Mô tả / hướng dẫn học<textarea aria-label="Mô tả bài giảng" rows={2} maxLength={10000} value={doc.description} onChange={e=>change(d=>({...d,description:e.target.value}))}/></label><div><p>Câu hỏi trong bài là luyện tập có phản hồi, không ghi điểm vào bảng điểm lớp.</p><button type="button" onClick={()=>run('Đang lưu bài giảng vào thư viện…',async()=>{const d=await save();const r=await apiClient.post(`${base}/${d._id}/publish`,{revision:d.revision});accept(r.data.draft);cache.invalidateQueries();setNotice('Đã lưu bài giảng vào thư viện E-learning.');})}>Lưu vào thư viện</button><button type="button" onClick={()=>run('Đang giao bài giảng…',async()=>{const d=await save();const r=await apiClient.post(`${base}/${d._id}/publish`,{revision:d.revision,assign:true});accept(r.data.draft);cache.invalidateQueries();setNotice('Đã lưu và giao bài giảng cho lớp.');})}>Lưu & giao cho lớp</button></div></div>
    </fieldset>
    {preview&&<div className="lesson-preview-overlay" role="dialog" aria-modal="true" aria-label="Xem thử bài giảng"><div><header><h3>Xem thử như học sinh</h3><button autoFocus onClick={()=>setPreview('')}>Đóng xem thử</button></header><iframe src={preview} title="Bài giảng xem thử" sandbox="allow-scripts allow-forms"/></div></div>}
  </section>;
}
