import {React,apiClient} from './runtime.js';

async function prepareImage(file){
  if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Chọn ảnh PNG, JPEG hoặc WebP tối đa 10 MB.');
  let bitmap;try{bitmap=await createImageBitmap(file);}catch{throw Error('Không đọc được ảnh. Hãy chọn một ảnh hợp lệ.');}
  try{
    const scale=Math.min(1,2000/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
    const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);
    const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('Không chuẩn bị được ảnh.');return new File([blob],'ai-material.jpg',{type:'image/jpeg'});
  }finally{bitmap.close();}
}
export function LessonAIAssistant({base,title,initialSource,onPrepare,onRun,onComplete,onClose}){
  const [topic,setTopic]=React.useState(initialSource?.topic||(title==='Bài giảng mới'?'':title)),[content,setContent]=React.useState(initialSource?.content||''),[images,setImages]=React.useState(initialSource?.images||[]),[slideCount,setSlideCount]=React.useState(initialSource?.slideCount||6),[questionCount,setQuestionCount]=React.useState(initialSource?.questionCount||3),[theme,setTheme]=React.useState(initialSource?.theme||'ocean');
  const input=React.useRef(null);
  const themes=[['ocean','Xanh dịu','#dcebf3'],['lavender','Tím nhạt','#e9dff4'],['warm','Vàng ấm','#f4e3c5']];
  return <section className="lesson-assistant" aria-label="AI hỗ trợ tạo bài giảng"><header><div><span className="lesson-assistant-badge">✦ GEMINI</span><h3>AI hỗ trợ</h3><p>Cung cấp tư liệu, AI sẽ soạn nội dung, bố trí ảnh và chèn trắc nghiệm vào bài giảng.</p></div><button type="button" className="secondary" onClick={onClose}>Đóng AI hỗ trợ</button></header>
    <form onSubmit={e=>{e.preventDefault();onRun('Gemini đang đọc tư liệu, soạn các trang và tạo trắc nghiệm…',async()=>{
      if(!topic.trim())throw Error('Nhập chủ đề bài học.');if(!content.trim()&&!images.length)throw Error('Nhập nội dung hoặc tải ảnh chứa tư liệu bài học.');
      const draft=await onPrepare();const response=await apiClient.post(`${base}/${draft._id}/generate-lesson`,{topic,content,images,slideCount,questionCount,theme},{timeout:180000});onComplete(response.data.draft);
    });}}><div className="lesson-assistant-grid"><div><label className="class-field">Chủ đề bài học<input required maxLength={200} value={topic} placeholder="Ví dụ: Cô bé bán diêm – Yêu thương và sẻ chia" onChange={e=>setTopic(e.target.value)}/></label><label className="class-field">Nội dung bài học<textarea aria-label="Nội dung bài học cho AI" rows={8} maxLength={20000} value={content} placeholder="Dán văn bản, kiến thức trọng tâm, mục tiêu và yêu cầu của bài học…" onChange={e=>setContent(e.target.value)}/></label><p className="lesson-assistant-hint">Có thể dùng ảnh chụp nội dung bài học. AI đọc ảnh thực tế cùng phần mô tả; ảnh rõ nét giúp nhận diện chữ chính xác hơn.</p>
    <div className="lesson-material-header"><h4>Ảnh & nội dung của ảnh <span>{images.length}/6</span></h4><button type="button" className="secondary" disabled={images.length>=6} onClick={()=>input.current.click()}>＋ Thêm ảnh tư liệu</button><input ref={input} hidden type="file" multiple accept="image/png,image/jpeg,image/webp" aria-label="Ảnh tư liệu cho AI" onChange={e=>{const files=[...e.target.files];e.target.value='';if(!files.length)return;onRun('Đang chuẩn bị và tải ảnh tư liệu…',async()=>{
      if(images.length+files.length>6)throw Error('Mỗi lần soạn bài dùng tối đa 6 ảnh.');const draft=await onPrepare();
      for(const file of files){const prepared=await prepareImage(file),body=new FormData();body.set('image',prepared);const result=await apiClient.post(`${base}/${draft._id}/images`,body,{headers:{'Content-Type':'multipart/form-data'}});setImages(list=>[...list,{url:result.data.url,caption:''}]);}
      setSlideCount(n=>Math.max(n,images.length+files.length));
    });}}/></div>
    {!images.length&&<div className="lesson-material-empty">Thêm tranh minh họa hoặc ảnh chụp trang sách. Có thể tạo bài chỉ từ nội dung chữ.</div>}
    <div className="lesson-materials">{images.map((image,i)=><article key={image.url}><img src={image.url} alt={`Ảnh tư liệu ${i+1}`}/><div><label className="class-field">Nội dung / mô tả ảnh {i+1}<textarea aria-label={`Mô tả ảnh ${i+1}`} rows={3} maxLength={2000} value={image.caption} placeholder="Ảnh nói về điều gì? Điểm nào cần nhấn mạnh trong bài giảng?" onChange={e=>setImages(list=>list.map((v,j)=>j===i?{...v,caption:e.target.value}:v))}/></label><button type="button" className="secondary" onClick={()=>setImages(list=>list.filter((_,j)=>j!==i))}>Bỏ ảnh {i+1}</button></div></article>)}</div></div>
    <aside className="lesson-assistant-settings"><h4>Thiết lập bài giảng</h4><label className="class-field">Số trang nội dung<select aria-label="Số trang AI tạo" value={slideCount} onChange={e=>setSlideCount(Number(e.target.value))}>{Array.from({length:9},(_,i)=>i+4).filter(n=>n>=images.length).map(n=><option key={n} value={n}>{n} trang</option>)}</select></label><label className="class-field">Trắc nghiệm trong bài<select aria-label="Số câu trắc nghiệm AI" value={questionCount} onChange={e=>setQuestionCount(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} câu hỏi</option>)}</select></label><fieldset><legend>Tông màu</legend>{themes.map(([value,label,color])=><label key={value} className="lesson-theme"><input type="radio" name="ai-lesson-theme" value={value} checked={theme===value} onChange={()=>setTheme(value)}/><i style={{background:color}}/>{label}</label>)}</fieldset><div className="lesson-assistant-summary"><b>{slideCount+questionCount} trang hoàn chỉnh</b><p>{slideCount} trang nội dung và {questionCount} trang câu hỏi, chèn sau phần kiến thức liên quan.</p><p>Có đáp án và giải thích. Bạn sửa được mọi khung chữ, ảnh và câu hỏi trong trình kéo thả.</p></div><button type="submit">✦ Tạo bài giảng bằng AI</button><small>Kết quả được lưu thành bản nháp mới. Chỉ đưa tới học sinh khi bạn chọn lưu vào thư viện hoặc giao bài.</small></aside></div></form>
  </section>;
}
