import { React, apiClient, useQueryClient } from './runtime.js';
import './storybook-studio.css';

const steps = [
  ['Ý tưởng câu chuyện', 'Nhập chủ đề và nội dung', '#245fa5'],
  ['Prompt cho 6 cảnh', 'Sao chép sang Gemini', '#7040a0'],
  ['Ảnh minh họa', 'Tải ảnh đúng từng cảnh', '#9a6010'],
  ['Dựng & xem thử', 'Lời kể trên trang sách', '#137866'],
  ['Lưu & giao bài', 'Đưa sách đến học sinh', '#a53d64'],
];
export function StorybookStudio({ classId }) {
  const cache = useQueryClient();
  const base = `/classes/${classId}/storybook-studio`;
  const [drafts,setDrafts] = React.useState([]), [draft,setDraft] = React.useState(null);
  const [step,setStep] = React.useState(0), [busy,setBusy] = React.useState(''), [error,setError] = React.useState(''), [notice,setNotice] = React.useState('');
  const [ready,setReady] = React.useState(null), [dirty,setDirty] = React.useState(false);
  const [form,setForm] = React.useState({title:'',content:'',style:'Tranh màu nước dịu nhẹ, ánh sáng ấm áp, nhân vật nhất quán, phù hợp học sinh lớp 6.'});
  const accept = d => { setDraft(d);setDirty(false);setDrafts(list=>[d,...list.filter(x=>x._id!==d._id)]);return d; };
  React.useEffect(()=>{
    let active=true;
    setDraft(null);setStep(0);setDrafts([]);
    apiClient.get(base).then(r=>{if(active){setDrafts(r.data.drafts);setReady(r.data.aiReady);}}).catch(e=>{if(active)setError(e.response?.data?.error||'Không tải được bản nháp.');});
    return ()=>{active=false;};
  },[base]);
  const run = async(label,fn) => {
    setBusy(label);setError('');setNotice('');
    try {await fn();}catch(e){setError(e.response?.data?.error||e.message||'Không thể thực hiện. Vui lòng thử lại.');}finally{setBusy('');}
  };
  const post = async(suffix,data={})=>accept((await apiClient.post(`${base}/${draft._id}${suffix}`,data,{timeout:180000, ...(data instanceof FormData ? {headers:{'Content-Type':'multipart/form-data'}} : {})})).data.draft);
  const saveEdits = async()=>{
    if(!dirty)return draft;
    return accept((await apiClient.patch(`${base}/${draft._id}`,{scenes:draft.scenes})).data.draft);
  };
  const editScene = (i,key,value)=>{setDraft(d=>({...d,previewUrl:null,scenes:d.scenes.map((s,j)=>i===j?{...s,[key]:value}:s)}));setDirty(true);};
  const open = d=>{accept(d);setNotice('');setError('');setStep(d.storybookId?4:d.previewUrl?3:d.scenes.length?2:0);};
  const available = i=>i===0||!!draft&&(i===1||i===2&&draft.scenes.length===6||i===3&&draft.scenes.length===6&&draft.scenes.every(s=>s.image)||i===4&&!!draft.previewUrl);
  const move = i=>run('Đang lưu…',async()=>{await saveEdits();setStep(i);});
  const uploaded=draft?.scenes.filter(s=>s.image).length||0;
  return <section className="studio" aria-label="Xưởng Story Book">
    <header className="studio-header"><div><span className="studio-eyebrow">GÓC SÁNG TẠO CỦA GIÁO VIÊN</span><h2>Tạo Story Book</h2><p>Từ một câu chuyện đến sáu trang sách minh họa.</p></div><button className="secondary" disabled={!!busy} onClick={()=>run('Đang lưu…',async()=>{await saveEdits();setDraft(null);setStep(0);setForm({title:'',content:'',style:form.style});})}>＋ Sách mới</button></header>
    <div className="studio-drafts"><label>Tiếp tục sách đã lưu<select aria-label="Tiếp tục bản nháp" value={draft?._id||''} disabled={!!busy} onChange={e=>{const d=drafts.find(d=>d._id===e.target.value);if(d)run('Đang lưu…',async()=>{await saveEdits();open(d);});}}><option value="">Chọn bản nháp hoặc sách đã hoàn tất</option>{drafts.map(d=><option value={d._id} key={d._id}>{d.title} · {d.storybookId?'Đã lưu sách':`${d.scenes.filter(s=>s.image).length}/6 ảnh`}</option>)}</select></label><span>{draft ? dirty?'Có thay đổi chưa lưu':'Bản nháp đã lưu' : 'Bắt đầu với một ý tưởng'}</span></div>
    {error&&<p className="class-error" role="alert">{error}</p>}{notice&&<p className="studio-notice" role="status">{notice}</p>}{busy&&<p className="studio-notice" role="status">{busy}</p>}
    {ready===false&&<p className="studio-notice">Gemini chưa được cấu hình. Quản trị viên cần thêm API key trong Cài đặt trợ lý AI. Bạn vẫn có thể lưu ý tưởng trước.</p>}
    <div className="studio-layout"><div className="studio-main" aria-busy={!!busy}>
      {step===0&&<form className="studio-panel" onSubmit={e=>{e.preventDefault();run('Đang lưu ý tưởng…',async()=>{if(!draft)accept((await apiClient.post(base,form)).data.draft);setStep(1);});}}><h3>01 · Câu chuyện bạn muốn kể</h3><p>Nhập nội dung gốc hoặc bản tóm tắt đủ diễn biến, nhân vật và kết thúc để AI chia cảnh chính xác.</p><label className="class-field">Chủ đề / tên sách<input required maxLength={150} placeholder="Ví dụ: Cô bé bán diêm" value={draft?.title??form.title} disabled={!!draft||!!busy} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="class-field">Nội dung câu chuyện<textarea required maxLength={20000} rows={10} placeholder="Dán nội dung hoặc viết bản tóm tắt câu chuyện tại đây…" value={draft?.content??form.content} disabled={!!draft||!!busy} onChange={e=>setForm({...form,content:e.target.value})}/></label><label className="class-field">Phong cách hình ảnh<textarea required maxLength={1000} value={draft?.style??form.style} disabled={!!draft||!!busy} onChange={e=>setForm({...form,style:e.target.value})}/></label><button disabled={!!busy}>Lưu ý tưởng & tiếp tục →</button></form>}
      {step===1&&<section className="studio-panel"><h3>02 · Bộ prompt cho 6 cảnh</h3><p>AI chia câu chuyện thành 6 cảnh và mô tả nhân vật nhất quán. Bạn có thể chỉnh prompt trước khi sao chép.</p>{!draft.scenes.length?<button disabled={!!busy} onClick={()=>run('Gemini đang chia 6 cảnh và viết prompt…',()=>post('/plan'))}>✦ Tạo 6 prompt bằng Gemini</button>:<><div className="studio-tip">Mở Gemini, dán lần lượt từng prompt để tạo ảnh. Tạo trong cùng cuộc trò chuyện và gửi lại ảnh nhân vật ở cảnh trước để giữ ngoại hình nhất quán. Chọn ảnh dọc 2:3 (ví dụ 1024 × 1536 px), không chèn chữ, không cần chừa khoảng trống. Lời kể nằm bên dưới ảnh.</div><a href="https://gemini.google.com/app" target="_blank" rel="noreferrer" className="studio-external">Mở Gemini ↗</a>{draft.scenes.map((s,i)=><article className="studio-scene" key={i}><h4><span>{i+1}</span>Cảnh {i+1}</h4><label className="class-field">Tên cảnh {i+1}<input value={s.title} maxLength={100} disabled={!!busy||!!draft.storybookId} onChange={e=>editScene(i,'title',e.target.value)}/></label><label className="class-field">Prompt cảnh {i+1}<textarea aria-label={`Prompt cảnh ${i+1}`} rows={6} value={s.prompt} maxLength={5000} disabled={!!busy||!!draft.storybookId} onChange={e=>editScene(i,'prompt',e.target.value)}/></label><button type="button" className="secondary" disabled={!!busy} onClick={()=>run('Đang sao chép…',async()=>{try{await navigator.clipboard.writeText(s.prompt);setNotice(`Đã sao chép prompt cảnh ${i+1}.`);}catch{throw Error('Trình duyệt chưa cho sao chép. Hãy chọn nội dung trong ô prompt và nhấn Ctrl + C.');}})}>Sao chép prompt {i+1}</button></article>)}<button disabled={!!busy} onClick={()=>move(2)}>Lưu prompt & tải ảnh →</button></>}</section>}
      {step===2&&<section className="studio-panel"><h3>03 · Ảnh của sáu cảnh <span className="class-tag">{uploaded}/6 ảnh</span></h3><p>Tải ảnh Gemini đã tạo vào đúng cảnh. PNG, JPEG hoặc WebP, tối đa 10 MB mỗi ảnh. Có thể thay ảnh trước khi lưu sách.</p><div className="studio-images">{draft.scenes.map((s,i)=><article className="studio-image-card" key={i}><div className="studio-image-preview">{s.image?<img src={s.image} alt={`Cảnh ${i+1}: ${s.title}`}/>:<span>＋<small>Ảnh cảnh {i+1}</small></span>}</div><h4>Cảnh {i+1} · {s.title}</h4><details><summary>Xem prompt</summary><p>{s.prompt}</p></details><label className="class-field">{s.image?'Thay ảnh':'Tải ảnh'} cảnh {i+1}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy||!!draft.storybookId} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;run(`Đang tải ảnh cảnh ${i+1}…`,async()=>{if(file.size>10*1024*1024)throw Error('Ảnh vượt quá 10 MB. Hãy chọn ảnh nhỏ hơn.');let bitmap;try{bitmap=await createImageBitmap(file);}catch{throw Error('Không đọc được ảnh. Hãy chọn ảnh PNG, JPEG hoặc WebP hợp lệ.');}bitmap.close();await saveEdits();const form=new FormData();form.append('image',file);await post(`/scenes/${i}/image`,form);});}}/></label></article>)}</div><button disabled={!!busy||uploaded!==6} onClick={()=>move(3)}>Tiếp tục dựng sách →</button></section>}
      {step===3&&<section className="studio-panel"><h3>04 · Lời kể & trang sách</h3><p>Gemini viết lời kể dựa trên nội dung và mô tả 6 cảnh. Hệ thống đặt tiêu đề và lời kể bên dưới ảnh, giữ nguyên toàn bộ tranh; bạn xem lại sự phù hợp giữa tranh và lời trước khi lưu.</p>{!draft.storybookId&&<div className="class-actions"><button disabled={!!busy} onClick={()=>run('Gemini đang viết lời kể và dựng sách…',async()=>{await saveEdits();await post('/render',{generateNarration:true});})}>✦ Gemini viết lời & dựng sách</button><button className="secondary" disabled={!!busy} onClick={()=>run('Đang dựng bản xem thử…',async()=>{await saveEdits();await post('/render');})}>Dựng từ lời kể hiện tại</button></div>}{draft.previewUrl&&<iframe className="studio-preview" title="Xem thử Story Book" src={draft.previewUrl} sandbox="allow-scripts allow-forms"/>}<details className="studio-narrations" open={!draft.previewUrl}><summary>Chỉnh lời kể của 6 cảnh</summary>{draft.scenes.map((s,i)=><label className="class-field" key={i}>Cảnh {i+1} · {s.title}<textarea maxLength={450} rows={4} value={s.narration} disabled={!!busy||!!draft.storybookId} onChange={e=>editScene(i,'narration',e.target.value)}/><small>{s.narration.length}/450 ký tự</small></label>)}</details><button disabled={!!busy||!draft.previewUrl||dirty} onClick={()=>move(4)}>Đã xem thử · Tiếp tục →</button></section>}
      {step===4&&<section className="studio-panel studio-finish"><span className="studio-finish-icon">✓</span><h3>{draft.storybookId?'Sách đã được lưu':'Sẵn sàng đưa vào thư viện'}</h3><h2>{draft.title}</h2><p>6 cảnh minh họa · Có lời kể bên dưới ảnh · Lật trang và đọc thành tiếng</p><p>Lưu sách để dùng trong thư viện, hoặc lưu và giao ngay cho học sinh trong lớp này.</p><div className="class-actions"><button disabled={!!busy||!!draft.storybookId} onClick={()=>run('Đang lưu sách…',async()=>{await post('/publish');cache.invalidateQueries();setNotice('Đã lưu Story Book vào thư viện.');})}>Lưu vào thư viện</button><button disabled={!!busy} onClick={()=>run('Đang lưu và giao sách…',async()=>{await post('/publish',{assign:true});cache.invalidateQueries();setNotice('Đã giao sách cho lớp. Học sinh có thể mở trong Bài được giao.');})}>Lưu & giao cho lớp</button></div>{draft.storybookId&&<a className="studio-external" href={`/storybooks/${draft.storybookId}`} target="_blank" rel="noreferrer">Mở sách trong thư viện ↗</a>}</section>}
    </div><aside className="studio-steps" aria-label="Các bước tạo Story Book"><h3>HÀNH TRÌNH TẠO SÁCH</h3>{steps.map(([title,description,color],i)=><button key={title} style={{'--step-color':color}} className={`studio-step ${step===i?'is-current':''}`} aria-current={step===i?'step':undefined} disabled={!!busy||!available(i)} onClick={()=>move(i)}><span className="studio-step-number">{String(i+1).padStart(2,'0')}</span><span><strong>{title}</strong><small>{description}</small></span></button>)}<div className="studio-help"><b>Mẹo tạo tranh đồng nhất</b><p>Giữ nguyên mô tả nhân vật trong cả 6 prompt. Dùng ảnh đầu làm tham chiếu cho những cảnh tiếp theo.</p></div></aside></div>
  </section>;
}
