import {useTeacherDraft} from './useTeacherDraft.js';
import {React,apiClient,useQueryClient} from './runtime.js';
import {ClassroomQuizQuestions} from './ClassroomQuizQuestions.jsx';
import './teacher-assessments.css';
const uid=()=>crypto.randomUUID();
const options=()=>Array.from({length:4},()=>({id:uid(),content:''}));
const question=(type='multiple_choice')=>({id:uid(),type,content:'',points:type==='essay'?2:1,options:type==='essay'?[]:options(),correctAnswer:0,explanation:'',hint:''});
const initial=()=>({title:'',description:'',duration:30,questions:[question()]});
const fields=q=>({title:q.title,description:q.description||'',duration:q.duration,questions:structuredClone(q.questions)});
export function TeacherAssessments({classId}){
  const base=`/classes/${classId}/teacher-assessments`,cache=useQueryClient();
  const [form,setForm]=useTeacherDraft(base,'form',initial),[saved,setSaved]=useTeacherDraft(base,'saved',null),[quizzes,setQuizzes]=React.useState([]),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[preview,setPreview]=React.useState(false),[previewAnswers,setPreviewAnswers]=React.useState({}),[assignment,setAssignment]=React.useState(null),[dueAt,setDueAt]=useTeacherDraft(base,'dueAt',''),[maxAttempts,setMaxAttempts]=useTeacherDraft(base,'maxAttempts',1),[instructions,setInstructions]=useTeacherDraft(base,'instructions','');
  const total=form.questions.reduce((sum,q)=>sum+(Number(q.points)||0),0),mc=form.questions.filter(q=>q.type==='multiple_choice').length;
  React.useEffect(()=>{let active=true;apiClient.get(base).then(r=>{if(active)setQuizzes(r.data.quizzes);}).catch(()=>{if(active)setError('Không tải được các đề đã lưu.');});return()=>{active=false;};},[base]);
  React.useEffect(()=>{if(!preview)return;const previous=document.activeElement,handler=e=>{if(e.key==='Escape')setPreview(false);},focus=e=>{const dialog=document.querySelector('.assessment-preview');if(dialog&&!dialog.contains(e.target))dialog.querySelector('button')?.focus();};document.addEventListener('keydown',handler);document.addEventListener('focusin',focus);return()=>{document.removeEventListener('keydown',handler);document.removeEventListener('focusin',focus);previous?.focus?.();};},[preview]);
  const update=(index,patch)=>setForm(f=>({...f,questions:f.questions.map((q,i)=>i===index?{...q,...patch}:q)}));
  const move=(from,to)=>setForm(f=>{const questions=[...f.questions];[questions[from],questions[to]]=[questions[to],questions[from]];return {...f,questions};});
  const open=q=>{setSaved(q);setForm(fields(q));setError('');setNotice('');setAssignment(null);setDueAt('');setMaxAttempts(1);setInstructions('');};
  const add=type=>setForm(f=>({...f,questions:[...f.questions,question(type)]}));
  return <section className="teacher-assessments" aria-label="Soạn kiểm tra đánh giá"><header className="assessment-header"><div><h2>Kiểm tra đánh giá</h2><p>Soạn đề trắc nghiệm, tự luận và giao cho học sinh làm theo mẫu hiện tại.</p></div><button className="secondary" disabled={busy} onClick={()=>{setForm(initial());setSaved(null);setNotice('');setError('');setAssignment(null);setDueAt('');setMaxAttempts(1);setInstructions('');}}>＋ Đề mới</button></header>
    {error&&<p className="class-error" role="alert">{error}</p>}{notice&&<p className="assessment-success" role="status">{notice}{assignment&&<> <a href={`/assignments/${assignment._id}`} target="_blank" rel="noreferrer">Mở bài đã giao ↗</a></>}</p>}
    <label className="class-field assessment-existing">Mở đề đã lưu<select aria-label="Mở đề kiểm tra đã lưu" value={saved?._id||''} disabled={busy} onChange={e=>{const q=quizzes.find(q=>q._id===e.target.value);if(q)open(q);}}><option value="">Chọn đề để xem hoặc chỉnh sửa</option>{quizzes.map(q=><option value={q._id} key={q._id}>{q.title} · {q.questions.length} câu · {q.totalPoints} điểm</option>)}</select></label>
    <form onSubmit={async e=>{e.preventDefault();const assign=e.nativeEvent.submitter?.value==='assign';setBusy(true);setError('');setNotice('');try{const body={...form,revision:saved?.revision||1,assign,maxAttempts,instructions,dueAt:assign&&dueAt?new Date(dueAt).toISOString():null};const r=await apiClient[saved?'patch':'post'](saved?`${base}/${saved._id}`:base,body);setSaved(r.data.quiz);setForm(fields(r.data.quiz));setQuizzes(list=>[r.data.quiz,...list.filter(q=>q._id!==r.data.quiz._id)]);setAssignment(r.data.assignment||null);setNotice(assign?'Đã lưu và giao đề cho lớp. Học sinh mở trong Bài được giao.':'Đã lưu đề kiểm tra.');cache.invalidateQueries();}catch(e){setError(e.response?.data?.error||'Không lưu được đề. Nội dung đang nhập vẫn được giữ.');}finally{setBusy(false);}}}>
    <fieldset className="assessment-fields" disabled={busy}><div className="assessment-layout"><div>
    <section className="assessment-panel"><h3>Thông tin đề</h3><label className="class-field">Tên bài kiểm tra<input required maxLength={200} value={form.title} placeholder="Ví dụ: Kiểm tra đọc hiểu – Cô bé bán diêm" onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="class-field">Ngữ liệu / yêu cầu<textarea aria-label="Ngữ liệu và yêu cầu của đề" rows={7} maxLength={30000} value={form.description} placeholder="Dán đoạn văn, bài thơ hoặc yêu cầu chung để học sinh đọc trước khi trả lời…" onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="class-field">Thời gian làm bài (phút)<input required type="number" min={1} max={180} value={form.duration} onChange={e=>setForm({...form,duration:e.target.value===''?'':Number(e.target.value)})}/></label></section>
    {form.questions.map((q,i)=><section className="assessment-panel assessment-question" key={q.id}><header><h3>Câu {i+1}</h3><div className="assessment-order"><button type="button" className="secondary" disabled={i===0} aria-label={`Đưa câu ${i+1} lên`} onClick={()=>move(i,i-1)}>↑</button><button type="button" className="secondary" disabled={i===form.questions.length-1} aria-label={`Đưa câu ${i+1} xuống`} onClick={()=>move(i,i+1)}>↓</button><button type="button" className="secondary" disabled={form.questions.length===1} aria-label={`Xóa câu ${i+1}`} onClick={()=>setForm({...form,questions:form.questions.filter((_,j)=>j!==i)})}>Xóa</button></div></header><div className="assessment-question-meta"><label className="class-field">Loại câu {i+1}<select value={q.type} onChange={e=>update(i,{type:e.target.value,options:e.target.value==='essay'?[]:options(),correctAnswer:0,points:e.target.value==='essay'?2:1})}><option value="multiple_choice">Trắc nghiệm</option><option value="essay">Tự luận</option></select></label><label className="class-field">Điểm câu {i+1}<input required type="number" min={0.25} max={100} step={0.25} value={q.points} onChange={e=>update(i,{points:e.target.value===''?'':Number(e.target.value)})}/></label></div><label className="class-field">Nội dung câu {i+1}<textarea aria-label={`Nội dung câu ${i+1}`} required maxLength={8000} rows={3} value={q.content} onChange={e=>update(i,{content:e.target.value})}/></label>
    {q.type==='multiple_choice'?<><p className="assessment-hint">Tích chọn một đáp án đúng để hệ thống tự chấm.</p><div className="assessment-options">{q.options.map((o,j)=><div className={q.correctAnswer===j?'correct':''} key={o.id}><label className="assessment-correct"><input type="radio" name={`correct-${q.id}`} checked={q.correctAnswer===j} onChange={()=>update(i,{correctAnswer:j})} aria-label={`Chọn đáp án ${String.fromCharCode(65+j)} cho câu ${i+1}`}/><b>{String.fromCharCode(65+j)}</b></label><input required aria-label={`Câu ${i+1} đáp án ${String.fromCharCode(65+j)}`} maxLength={2000} value={o.content} onChange={e=>update(i,{options:q.options.map((v,k)=>k===j?{...v,content:e.target.value}:v)})}/>{q.correctAnswer===j&&<span>Đúng</span>}</div>)}</div><label className="class-field">Giải thích đáp án câu {i+1}<textarea aria-label={`Giải thích câu ${i+1}`} maxLength={8000} value={q.explanation} onChange={e=>update(i,{explanation:e.target.value})}/></label></>:<><label className="class-field">Hướng dẫn chấm câu {i+1} (dành cho giáo viên)<textarea aria-label={`Hướng dẫn chấm câu ${i+1}`} maxLength={8000} value={q.explanation} placeholder="Đáp án tham khảo, các ý cần đạt và cách chia điểm…" onChange={e=>update(i,{explanation:e.target.value})}/></label><label className="class-field">Gợi ý câu {i+1} (học sinh nhìn thấy)<input maxLength={2000} value={q.hint} onChange={e=>update(i,{hint:e.target.value})}/></label></>}
    </section>)}
    <div className="assessment-add"><button type="button" className="secondary" disabled={form.questions.length>=100} onClick={()=>add('multiple_choice')}>＋ Thêm trắc nghiệm</button><button type="button" className="secondary" disabled={form.questions.length>=100} onClick={()=>add('essay')}>＋ Thêm tự luận</button></div></div>
    <aside className="assessment-summary"><h3>Tổng quan đề</h3><div className="assessment-stats"><div><strong>{form.questions.length}</strong><span>câu hỏi</span></div><div><strong>{Number(total.toFixed(2))}</strong><span>tổng điểm</span></div><div><strong>{form.duration||0}</strong><span>phút</span></div></div><p>{mc} trắc nghiệm · {form.questions.length-mc} tự luận</p><p className="assessment-hint">Trắc nghiệm tự chấm. Tự luận nằm trong mục Chấm tự luận để giáo viên cho điểm và trả bài.</p><button type="button" className="secondary" onClick={()=>{setPreviewAnswers({});setPreview(true);}}>Xem mẫu học sinh</button><details className="assessment-delivery" open><summary>Thiết lập giao bài</summary><label className="class-field">Hạn nộp (không bắt buộc)<input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label><label className="class-field">Số lượt làm tối đa<select aria-label="Số lượt làm tối đa" value={maxAttempts} onChange={e=>setMaxAttempts(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} lượt</option>)}</select></label><label className="class-field">Yêu cầu khi giao bài<textarea aria-label="Yêu cầu khi giao bài" rows={3} maxLength={2000} value={instructions} onChange={e=>setInstructions(e.target.value)}/></label></details><button type="submit" name="action" value="save">{busy?'Đang lưu…':'Lưu đề'}</button><button type="submit" name="action" value="assign">Lưu & giao cho lớp</button>{saved&&<p className="assessment-hint">Đề đã giao giữ nguyên nội dung. Bản chỉnh sửa được dùng cho lần giao mới.</p>}</aside></div></fieldset></form>
    {preview&&<div className="assessment-preview" role="dialog" aria-modal="true" aria-label="Mẫu bài làm học sinh"><div><header><div><h3>{form.title||'Bài kiểm tra'}</h3><p>{form.duration} phút · {form.questions.length} câu · {Number(total.toFixed(2))} điểm</p></div><button autoFocus onClick={()=>setPreview(false)}>Đóng xem thử</button></header><div className="assessment-preview-content"><p className="assessment-hint">Bản xem thử giao diện, không tạo lượt làm hoặc ghi điểm.</p><details className="class-panel" open><summary>Ngữ liệu và yêu cầu</summary><p className="preserve">{form.description}</p></details><ClassroomQuizQuestions questions={form.questions} answers={previewAnswers} namePrefix="preview-" onAnswer={(id,value)=>setPreviewAnswers(a=>({...a,[id]:value}))}/></div></div></div>}
  </section>;
}
