import {React,apiClient,useQueryClient} from './runtime.js';
import {videoLink} from '../../shared/video-links.js';
import './teacher-videos.css';
const sources=[['upload','Tải từ máy','Video MP4, WebM'],['drive','Google Drive','Dán link chia sẻ video'],['youtube','YouTube','Link xem hoặc Shorts']];
export function TeacherVideos({classId}){
  const cache=useQueryClient(),base=`/classes/${classId}/teacher-videos`;
  const [source,setSource]=React.useState('upload'),[title,setTitle]=React.useState(''),[description,setDescription]=React.useState(''),[url,setUrl]=React.useState(''),[file,setFile]=React.useState(null),[local,setLocal]=React.useState(''),[assign,setAssign]=React.useState(false);
  const [busy,setBusy]=React.useState(false),[progress,setProgress]=React.useState(0),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[videos,setVideos]=React.useState([]),[selected,setSelected]=React.useState(null),[version,setVersion]=React.useState(0);
  React.useEffect(()=>{let active=true;apiClient.get(base).then(r=>{if(active)setVideos(r.data.videos);}).catch(()=>{if(active)setError('Không tải được danh sách video.');});return()=>{active=false;};},[base]);
  React.useEffect(()=>{if(!file){setLocal('');return;}const value=URL.createObjectURL(file);setLocal(value);return()=>URL.revokeObjectURL(value);},[file]);
  let embed='',linkError='';
  if(source!=='upload'&&url.trim())try{embed=videoLink(url,source).embed;}catch(e){linkError=e.message;}
  let savedEmbed='';if(selected&&selected.source!=='upload')try{savedEmbed=videoLink(selected.url,selected.source).embed;}catch{}
  const reset=()=>{setTitle('');setDescription('');setUrl('');setFile(null);setSelected(null);setNotice('');setError('');setAssign(false);setVersion(v=>v+1);};
  return <section className="teacher-videos" aria-label="Quản lý Video minh họa"><header className="video-form-header"><div><h2>Video minh họa</h2><p>Thêm video để học sinh xem và học cùng câu chuyện.</p></div><button className="secondary" disabled={busy} onClick={reset}>＋ Video mới</button></header>
    {error&&<p role="alert" className="class-error">{error}</p>}{notice&&<p role="status" className="video-success">{notice}</p>}
    <div className="teacher-video-layout"><form className="video-form-panel" onSubmit={async e=>{e.preventDefault();setError('');setNotice('');if(source==='upload'&&!file){setError('Hãy chọn video từ máy.');return;}if(source!=='upload'&&(!embed||linkError)){setError(linkError||'Hãy nhập link video.');return;}setBusy(true);setProgress(0);try{const body=new FormData();body.set('title',title);body.set('description',description);body.set('source',source);body.set('assign',String(assign));if(source==='upload')body.set('file',file);else body.set('url',url);const r=await apiClient.post(base,body,{headers:{'Content-Type':'multipart/form-data'},timeout:0,onUploadProgress:e=>{if(e.total)setProgress(Math.round(e.loaded/e.total*100));}});setVideos(v=>[r.data.video,...v]);setSelected(r.data.video);setNotice(r.data.assignment?'Đã lưu video và giao cho lớp.':'Đã lưu video vào thư viện. Có thể giao trong Bài được giao.');setTitle('');setDescription('');setUrl('');setFile(null);setVersion(v=>v+1);cache.invalidateQueries();}catch(e){setError(e.response?.data?.error||'Không lưu được video. Kiểm tra kết nối rồi thử lại.');}finally{setBusy(false);}}}>
      <h3>Thông tin video</h3><label className="class-field">Tiêu đề video<input required maxLength={200} value={title} disabled={busy} placeholder="Ví dụ: Cô bé bán diêm – video kể chuyện" onChange={e=>setTitle(e.target.value)}/></label><label className="class-field">Mô tả<textarea aria-label="Mô tả video" rows={5} maxLength={10000} value={description} disabled={busy} placeholder="Giới thiệu nội dung, mục tiêu hoặc câu hỏi gợi mở cho học sinh…" onChange={e=>setDescription(e.target.value)}/></label>
      <fieldset className="video-source-picker"><legend>Nguồn video</legend>{sources.map(([value,label,help])=><label key={value} className={source===value?'active':''}><input type="radio" name="video-source" value={value} checked={source===value} disabled={busy} onChange={()=>{setSource(value);setSelected(null);setError('');}}/><span><b>{label}</b><small>{help}</small></span></label>)}</fieldset>
      {source==='upload'?<label className="class-field video-upload">Chọn video từ máy<input key={version} type="file" accept="video/mp4,video/webm,.mp4,.webm" disabled={busy} onChange={e=>{const f=e.target.files?.[0];setSelected(null);setError('');if(f&&(!/\.(mp4|webm)$/i.test(f.name)||f.size>300*1024*1024)){setFile(null);e.target.value='';setError('Chọn MP4 hoặc WebM tối đa 300 MB. Video lớn hơn có thể dùng link Drive hoặc YouTube.');return;}setFile(f||null);}}/><small>{file?`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`:'MP4 hoặc WebM, tối đa 300 MB.'}</small></label>:<><label className="class-field">{source==='drive'?'Link Google Drive':'Link YouTube'}<input type="url" required maxLength={2000} value={url} disabled={busy} placeholder={source==='drive'?'https://drive.google.com/file/d/…/view':'https://www.youtube.com/watch?v=…'} onChange={e=>{setUrl(e.target.value);setSelected(null);}}/></label>{linkError&&<p className="class-error">{linkError}</p>}{source==='drive'?<p className="video-source-help">Trên Drive, chọn video → Chia sẻ → cấp quyền Người xem cho học sinh hoặc “Bất kỳ ai có đường liên kết”. Dán link tệp video, không phải thư mục. Video vẫn được lưu trên Drive.</p>:<p className="video-source-help">Dán link YouTube, youtu.be hoặc Shorts. Video cần cho phép nhúng để phát trực tiếp trong bài học.</p>}</>}
      <label className="video-assign"><input type="checkbox" checked={assign} disabled={busy} onChange={e=>setAssign(e.target.checked)}/>Giao video này cho lớp ngay sau khi lưu</label>
      {busy&&<div role="status"><p>{progress<100?`Đang tải lên… ${progress}%`:'Đang lưu video…'}</p><progress value={progress} max={100} aria-label="Tiến độ tải video"/></div>}<button disabled={busy}>{busy?'Đang lưu…':assign?'Lưu & giao cho lớp':'Lưu video'}</button>
    </form><aside className="video-preview-panel"><h3>Xem trước</h3><div className="teacher-video-player">{selected?(savedEmbed?<iframe title="Xem video đã lưu" src={savedEmbed} allow="fullscreen; autoplay" allowFullScreen/>:<video title="Video đã lưu" src={selected.url} controls preload="metadata"/>):source==='upload'&&local?<video title="Xem trước video tải lên" src={local} controls preload="metadata" onError={()=>setError('Trình duyệt chưa đọc được video này. Thử MP4 mã hóa H.264 hoặc WebM.')} />:embed?<iframe title="Xem trước video liên kết" src={embed} allow="fullscreen; autoplay" allowFullScreen/>:<div className="video-preview-empty"><span>▷</span><p>Chọn tệp hoặc dán link để xem trước video.</p></div>}</div><h4>{selected?.title||title||'Tiêu đề video'}</h4><p className="video-description">{selected?.description||description||'Mô tả video sẽ hiển thị tại đây.'}</p>{selected&&<a className="class-link" href={`/video/${selected._id}`} target="_blank" rel="noreferrer">Mở trang video ↗</a>}</aside></div>
    <section className="teacher-video-list"><h3>Video đã thêm trong lớp <span className="class-tag">{videos.length}</span></h3>{!videos.length?<p>Chưa có video. Thêm video đầu tiên bằng form phía trên.</p>:<div className="class-grid">{videos.map(v=><article className="class-panel" key={v._id}><span className="class-tag">{sources.find(s=>s[0]===v.source)?.[1]||'Video'}</span><h4>{v.title}</h4><p>{v.description}</p><button className="secondary" disabled={busy} onClick={()=>{setSelected(v);document.querySelector('.video-preview-panel')?.scrollIntoView({behavior:'smooth',block:'center'});}}>Xem video</button></article>)}</div>}</section>
  </section>;
}
