import { chromium } from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { startTestServer } from '../tests/support.mjs';
const server = await startTestServer({ ai: true });
const executablePath = process.env.BROWSER_PATH || ['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Google/Chrome/Application/chrome.exe'].find(p => fs.existsSync(p));
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(executablePath ? { executablePath } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', dialog => dialog.accept());
  await page.goto(server.base + '/login');
  await page.locator('input').first().fill('admin');
  await page.locator('input[type="password"]').fill('Incorrect!2026');
  await page.locator('button[type="submit"]').click();
  await page.getByText('Sai tên đăng nhập hoặc mật khẩu', { exact: true }).waitFor();
  assert.equal(new URL(page.url()).pathname, '/login');
  console.log('PASS invalid login displays an error without reloading');
  await page.locator('input[type="password"]').fill('ReviewAdmin!2026');
  await page.locator('button[type="submit"]').click();
  await page.waitForURL(server.base + '/');
  fs.mkdirSync('artifacts/browser', { recursive: true });
  for (const route of ['/', '/storybooks', `/storybooks/${server.fixtures.story._id}`, '/videos', '/elearnings', '/quizzes', '/my-results', '/my-flashcards', '/profile', '/admin', '/admin/users', '/admin/categories', '/admin/storybooks', '/admin/videos', '/admin/elearnings', '/admin/quizzes', '/admin/quiz-results', '/admin/banners', '/admin/ai-settings']) {
    await page.goto(server.base + route); await page.waitForLoadState('networkidle');
    assert.equal(new URL(page.url()).pathname, route, `Unexpected redirect: ${route}`);
    assert.ok((await page.locator('#root').innerText()).length > 40, `Empty page: ${route}`);
    console.log('PASS page', route);
  }
  await page.goto(`${server.base}/quiz/${server.fixtures.quiz._id}`);
  await page.getByRole('button', { name: /Bắt đầu/ }).click();
  await page.locator('input[type="radio"]').first().check();
  await page.locator('textarea').fill('Em học được tính trung thực.');
  await page.getByRole('button', { name: /Nộp bài/ }).click();
  await page.getByText('Đã nộp bài!', { exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/browser/quiz-result.png', fullPage: true });
  assert.ok(await page.getByText('Tiều phu', { exact: false }).count());
  console.log('PASS quiz interaction and results');
  await page.goto(`${server.base}/storybooks/${server.fixtures.story._id}`);
  await page.getByRole('button', { name: /Flash Card AI/ }).click();
  await page.getByRole('button', { name: /Tạo Flash Card/ }).click();
  await page.getByText('Câu hỏi 1', { exact: true }).waitFor();
  const paper = page.getByTestId('flashcard-paper');
  await paper.getByRole('button').click();
  await page.waitForFunction(() => document.querySelector('.flash-paper-leaf')?.getAnimations().length > 0);
  await page.waitForTimeout(200);
  await page.screenshot({ path: 'artifacts/browser/flashcard-turn.png' });
  await page.waitForFunction(() => document.querySelector('.flash-paper')?.dataset.turning === 'false');
  assert.equal(await paper.getAttribute('data-face'), 'answer');
  await paper.getByRole('button').press('Space');
  assert.equal(await paper.getAttribute('data-face'), 'question');
  await page.keyboard.press('ArrowRight');
  await paper.getByRole('button').getByText('Câu hỏi 2', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Đến thẻ 1', exact: true }).click();
  await page.getByRole('button', { name: /Lưu Flash Card/ }).click();
  await page.getByText(/Đã lưu/).waitFor();
  await page.screenshot({ path: 'artifacts/browser/flashcards.png', fullPage: true });
  console.log('PASS flashcard generation and save');
  await page.goto(`${server.base}/storybooks/${server.fixtures.story._id}`);
  const reader = page.frameLocator('iframe');
  await reader.getByRole('button', { name: 'Trang sau', exact: true }).click();
  await reader.locator('#book[data-turning="true"]').waitFor();
  await page.screenshot({ path: 'artifacts/browser/reader-turn.png' });
  await reader.getByText('2 / 6', { exact: true }).waitFor();
  assert.ok(await reader.locator('.stf__wrapper.--portrait').count());
  await page.screenshot({ path: 'artifacts/browser/reader.png', fullPage: true });
  console.log('PASS story page navigation');
  await page.getByRole('button', { name: /Trắc nghiệm AI/ }).click();
  await page.getByRole('button', { name: 'Bắt đầu', exact: true }).click();
  for (let i = 0; i < 5; i++) {
    await page.getByRole('button', { name: /Tiều phu/ }).click();
    if (i < 4) await page.getByRole('button', { name: 'Tiếp', exact: true }).click();
  }
  await page.getByRole('button', { name: 'Nộp bài', exact: true }).click();
  await page.getByText('100%', { exact: true }).waitFor();
  console.log('PASS AI story quiz and result');
  const course = await server.request('POST', '/elearnings', { title: 'Đọc hiểu truyện dân gian', url: '/reference/lesson.html' }, server.adminToken);
  await page.goto(`${server.base}/elearning/${course.data.elearning._id}`);
  const lesson = page.frameLocator('iframe');
  await lesson.getByRole('button', { name: /Cùng luyện tập/ }).click();
  await lesson.getByLabel('Tự sự', { exact: true }).check();
  await lesson.getByRole('button', { name: 'Kiểm tra', exact: true }).click();
  await lesson.getByRole('status').filter({ hasText: 'Đúng!' }).waitFor();
  console.log('PASS interactive lesson');
  await page.goto(server.base + '/');
  await page.getByRole('button', { name: /Hỏi kiến thức Ngữ Văn 6/ }).click();
  await page.getByPlaceholder('Hỏi bất cứ điều gì về Ngữ Văn 6...').fill('Thế nào là từ đơn?');
  await page.getByPlaceholder('Hỏi bất cứ điều gì về Ngữ Văn 6...').press('Enter');
  await page.getByText(/Từ đơn là từ chỉ có một tiếng/).waitFor();
  console.log('PASS literature chat');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(server.base + '/storybooks'); await page.waitForLoadState('networkidle');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'Mobile horizontal overflow');
  await page.screenshot({ path: 'artifacts/browser/mobile.png', fullPage: true });
  assert.deepEqual(errors, [], 'Browser runtime errors');
  console.log('PASS mobile layout and zero runtime errors');
  for (const width of [1505, 1024, 390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    await page.goto(`${server.base}/storybooks/${server.fixtures.story._id}`);
    await page.locator('.story-tools').waitFor();
    const toggle = page.getByRole('button', { name: 'Mở công cụ AI', exact: true });
    if (await toggle.count()) await toggle.click();
    await page.getByRole('button', { name: /Flash Card AI/ }).waitFor();
    const bounds = await page.locator('.story-tools').boundingBox();
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= width, `AI tools clipped at ${width}`);
    await page.getByRole('button', { name: /Flash Card AI/ }).click();
    await page.getByTestId('flashcard-paper').waitFor();
    const modal = await page.getByRole('dialog').boundingBox();
    assert.ok(modal.x >= 0 && modal.x + modal.width <= width && modal.y >= 0 && modal.y + modal.height <= 844);
    await page.keyboard.press('Escape');
    await page.getByRole('dialog').waitFor({ state: 'hidden' });
  }
  assert.deepEqual(errors, [], 'Browser runtime errors after responsive checks');
  console.log('PASS animated reader, flashcard keyboard and responsive tools/dialog at four widths');
} finally { await browser?.close(); await server.stop(); }
